config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup' , to: 'users#new'
  resources :users, except: [:new]
  # post 'users' , to: 'users#create', as: :users
  #get 'user/:id' , to: 'users#show', as: :user
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 4, maximum: 50 }
  validates :description, presence: true, length: { minimum: 6, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :username, presence: true, 
  uniqueness: { case_sensitive: false }, 
  length: { minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
  uniqueness: { case_sensitive: false }, 
  length: { maximum: 105 },
  format: { with: VALID_EMAIL_REGEX }

  has_secure_password
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
      !!current_user
  end

  def require_user
      if !logged_in?
          flash[:alert] = 'You must be logged in.'
          redirect_to login_path
      end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    
  end
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end
  
  def new
    @article = Article.new

  end

  def edit
    
  end

  def create
    @article = Article.new(article_params)
     @article.user = current_user
    if @article.save
      flash[:notice] = "Article Created Successfully."
      redirect_to @article
    else
      render 'new' , status: :unprocessable_entity
    end
  end

  def update
    
    if @article.update(article_params)
      flash[:notice] = "Article Updated Successfully."
      redirect_to @article
    else
      render 'edit' , status: :unprocessable_entity
    end
  end

  def destroy
    
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Wrong Credentials"
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    # @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new 
    @user = User.new
  end

  def edit
    # @user = User.find(params[:id])
  
  end

  def update
    # @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Account succesfully Updated"
      redirect_to @user
    else
      render 'edit'
    end


  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, you have succesfully siggned-up "
      redirect_to articles_path
    else
      render 'new' , status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :age, :password, :avatar)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
  <%= article.user.id + "to" + current_user.id%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div> 
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Oops Errors-</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>
<%= image_tag("aboutimages/articles.jpg") %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
         <% if logged_in? && article.user == current_user %> 
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: { turbo_method: :delete}  %></td>
         <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>
<p>
  <%= link_to 'Create new article', new_article_path %> 
</p>
<%= link_to 'Home Page', root_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1> Showing Article Details </h1>

<%# <div class="card-text text-left"><%= simple_format(@article.description) %></div> 
          <% if logged_in? && @article.user == current_user %>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Return to articles listing', articles_path %>


app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %> 

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="
#bs-example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Navigation Bar</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to 'Home Page', root_path %> |
<%= link_to 'Articles Listing', articles_path %> |
<%# <%= link_to 'Users', users_path %>  
<%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %> 
<% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        </li>
        <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
       
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <%# <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li> 
      <% end %>
      </ul>
</div>


<div class="collapse navbar-collape" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
  </ul>
  </div>
  </div>
  </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href = "https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>
  
  <header>
      <%= render 'layouts/navbar' %>
  </header>

  <body>

   <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to About Page</h1> 
<%= image_tag("aboutimages/about.jpg") %>
<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb

<h1> Welcome to HomePage</h1>
<%= link_to 'Articles Listing', articles_path %> 
<%= link_to 'About Page', about_path %>
<%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
<%= link_to 'Log-in', login_path %>

app/views/shared/_errors.html.erb

    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :first_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :first_name, class: "form-control shadow rounded", placeholder: "Enter first name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :last_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :last_name, class: "form-control shadow rounded", placeholder: "Enter last name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :age, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.number_field :age, class: "form-control shadow rounded", placeholder: "Enter your Age" %>
          </div>
        </div>

        

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
        </div>
        <%= f.label :avatar, style: "display: block" %>
      <%= f.file_field :avatar %>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit your profile </h1>

<%= render 'form' %>


app/views/users/index.html.erb
<h1 class="text-center mt-4"> Users </h1>

<%= will_paginate @users %>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %> | 
            <% if logged_in? and user == current_user %>
              <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>  |
            <% end %>

            <% if logged_in? && current_user.admin? %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { turbo_method: :delete} %>
            <% end %>

          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign up </h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.username%>'s profile </h1>

<% if logged_in? && current_user.admin? %> 
<p> Show All Users- <%= link_to 'Users', users_path %> </p>
<% end %>


<i> Username- <%= @user.username%></i>
<i> Email- <%= @user.email%></i>
<i> First Name- <%= @user.first_name%></i>
<i> Last Name- <%= @user.last_name%></i>
<i> Age- <%= @user.age%></i>

<img src=<%= @user.avatar %> />

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %> |
    <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { turbo_method: :delete} %>
  </div>
<% end %>
</div>